{% set name = "kumoai" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  missing_dso_whitelist:
    - lib/libstdc++.so.6  # [linux and x86_64]
    - lib/libgcc_s.so.1  # [linux and x86_64]
    - /lib64/libm.so.6  # [linux and x86_64]
    - /lib64/libpthread.so.0  # [linux and x86_64]
    - /lib64/libc.so.6  # [linux and x86_64]
    - /lib64/ld-linux-x86-64.so.2  # [linux and x86_64]
  skip: true  # [py<310]

requirements:
  build:
    # curl is needed only for downloading whl files in build.sh and bld.bat
    - curl
  host:
    - pip
    - python
    - wheel
  run:
    - python
    - aiohttp >=3.10.0
    - pandas
    - plotly
    - pyarrow >=8.0.0,<19.0.0
    - requests >=2.28.2
    - rich >=9.0.0
    - tqdm >=4.66.0
    - urllib3
    - kumo-api ==0.45.0
    # kumolib.cpython-310-x86_64-linux-gnu.so - Dynamic Section:
    #  NEEDED       libstdc++.so.6
    #  NEEDED       libm.so.6
    #  NEEDED       libgcc_s.so.1
    #  NEEDED       libpthread.so.0
    #  NEEDED       libc.so.6
    #  NEEDED       ld-linux-x86-64.so.2
    # for libstdc++.so.6
    - libstdcxx-ng  # [linux and x86_64]
    # for libgcc_s.so.1
    - libgcc-ng  # [linux and x86_64]

# Unable to create some tests example with LLM, needs API TOKEN -> https://kumo-ai.github.io/kumo-sdk/docs/get_started/introduction.html#initializing-the-sdk
test:
  imports:
    - kumoai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kumo.ai
  summary: AI on the Modern Data Stack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    The Kumo SDK implements a pythonic interface for users to programmatically interact with the Kumo machine learning platform
  dev_url: https://pypi.org/project/kumoai
  doc_url: https://kumo-ai.github.io/kumo-sdk/docs/#

extra:
  recipe-maintainers:
    - aosipov